<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Discount') ?></h4>
     </div>
     <div class="fieldset">
            <p><input type="text" class="file_title" id="salesrule" value="<?php echo $this->escapeHtml($quoteModel->getCouponCodeById($quoteModel->getData('salesrule'))) ?>" name="salesrule" style="width:200px" />&nbsp;
            <?php $couponButton = true ?>
			<?php if (isset($couponButton) && $couponButton === true):
                        $vars = new Varien_Object;
                        $vars->setData('label', $this->__('Apply'));
                        echo $this->getSaveButton($vars)->_toHtml();
                    endif; ?>
            
            </p>
            
            <?php if ($quoteModel->getData('salesrule') != null): ?>
                <p><strong><?php echo $this->escapeHtml($quoteModel->getCouponNameById($quoteModel->getData('salesrule'))) ?></strong> [<a href="#" onclick="$('loading-mask').show();removeCoupon(); return false;" title="<?php echo Mage::helper('sales')->__('Remove Coupon Code') ?>"><?php echo Mage::helper('sales')->__('Remove') ?></a>]</p>
            <?php endif; ?>
    </div>
</div>

<script type="text/javascript">
function removeCoupon()
{
	$('salesrule').setValue('');
	save();
}

</script>