<ul class="messages">
    <li class="error-msg">
        <ul>
            <li>
                <span><?php echo Mage::helper('qquoteadv')->__('Please specify product quantity.')?></span>
            </li>
        </ul>
    </li>
</ul>

<div style="clear:both;">
    <br>
    <button type="button" onclick="javascript: cancelMsg();" title="Continue Shopping" class="button btn-cart">
        <span>
            <span><?php echo Mage::helper('qquoteadv')->__('Continue Shopping')?>'</span>
        </span>
    </button>

</div>